export const HOMEPAGE_MODULE_DEFINITIONS = [
  {
    type: "hero_board",
    label: "Hero Board",
    description: "Top league identity block with latest-session context.",
    allowedVariants: ["editorial_lead", "session_result", "league_board"],
    defaultVariant: "editorial_lead",
    allowedSourceModes: ["automatic", "latest", "manual", "league_board"],
    supportsManualSelection: true,
    manualSelectionType: "hero",
    minItems: 1,
    maxItems: 1,
    defaultItemLimit: 1,
    defaultTitle: "Para League",
    defaultDek: "The first sessions are setting the board.",
    allowSectionHeader: false,
  },
  {
    type: "stat_strip",
    label: "Stat Strip",
    description: "Quick public totals for sessions, players, moments, and leader.",
    allowedVariants: ["standard", "compact", "hidden_support"],
    defaultVariant: "standard",
    allowedSourceModes: ["automatic"],
    supportsManualSelection: false,
    minItems: 0,
    maxItems: 4,
    defaultItemLimit: 4,
    defaultTitle: "League Signals",
    defaultDek: "The public record in compact form.",
    allowSectionHeader: false,
  },
  {
    type: "latest_session",
    label: "Latest Session",
    description: "Current recap doorway with winner, hand count, and biggest pot.",
    allowedVariants: ["match_report", "result_strip", "editorial_brief"],
    defaultVariant: "match_report",
    allowedSourceModes: ["latest", "manual"],
    supportsManualSelection: true,
    manualSelectionType: "sessions",
    minItems: 1,
    maxItems: 1,
    defaultItemLimit: 1,
    defaultTitle: "Latest Session",
    defaultDek: "The newest approved table result.",
    allowSectionHeader: true,
  },
  {
    type: "upcoming_events",
    label: "Upcoming Events",
    description: "Future table cards staged by admin until the game-site schedule feed is connected.",
    allowedVariants: ["event_cards", "schedule_strip", "single_teaser"],
    defaultVariant: "event_cards",
    allowedSourceModes: ["automatic", "manual"],
    supportsManualSelection: true,
    manualSelectionType: "events",
    minItems: 1,
    maxItems: 4,
    defaultItemLimit: 2,
    defaultTitle: "Upcoming Tables",
    defaultDek: "Future events will appear here once staged by the league desk.",
    allowSectionHeader: true,
  },
  {
    type: "current_standings",
    label: "Current Standings",
    description: "Condensed season board linking to the full standings page.",
    allowedVariants: ["compact_board", "top_three", "pressure_watch"],
    defaultVariant: "compact_board",
    allowedSourceModes: ["automatic"],
    supportsManualSelection: false,
    minItems: 3,
    maxItems: 8,
    defaultItemLimit: 5,
    defaultTitle: "Current Board",
    defaultDek: "Rank and points stay tied to verified standings.",
    allowSectionHeader: true,
  },
  {
    type: "featured_players",
    label: "Featured Players",
    description: "Top public player cards from the active board.",
    allowedVariants: ["identity_rail", "profile_grid", "form_watch"],
    defaultVariant: "identity_rail",
    allowedSourceModes: ["automatic", "manual"],
    supportsManualSelection: true,
    manualSelectionType: "players",
    minItems: 1,
    maxItems: 6,
    defaultItemLimit: 3,
    defaultTitle: "Players To Know",
    defaultDek: "Names carrying the early public record.",
    allowSectionHeader: true,
  },
  {
    type: "featured_moments",
    label: "Featured Moments",
    description: "Notable hand cards from the moment archive.",
    allowedVariants: ["archive_clippings", "featured_moment", "compact_strip"],
    defaultVariant: "archive_clippings",
    allowedSourceModes: ["automatic", "latest", "manual"],
    supportsManualSelection: true,
    manualSelectionType: "moments",
    minItems: 1,
    maxItems: 6,
    defaultItemLimit: 3,
    defaultTitle: "Moments From The Archive",
    defaultDek: "Hands that left a visible mark.",
    allowSectionHeader: true,
  },
  {
    type: "latest_articles",
    label: "Latest Articles",
    description: "Published newsroom coverage module.",
    allowedVariants: ["headline_list", "lead_and_briefs", "three_column"],
    defaultVariant: "headline_list",
    allowedSourceModes: ["latest", "manual"],
    supportsManualSelection: true,
    manualSelectionType: "articles",
    minItems: 1,
    maxItems: 6,
    defaultItemLimit: 3,
    defaultTitle: "Latest Coverage",
    defaultDek: "Approved newsroom pieces from the league desk.",
    allowSectionHeader: true,
  },
  {
    type: "social_caption_block",
    label: "Social Caption",
    description: "A short published card/caption beat for sharing a league moment.",
    allowedVariants: ["quote_card", "compact_callout"],
    defaultVariant: "quote_card",
    allowedSourceModes: ["latest", "manual"],
    supportsManualSelection: true,
    manualSelectionType: "socialCaptions",
    minItems: 1,
    maxItems: 3,
    defaultItemLimit: 1,
    defaultTitle: "Social Beat",
    defaultDek: "Short-form league copy staged by the newsroom.",
    allowSectionHeader: true,
  },
  {
    type: "top_performers",
    label: "Top Performers",
    description: "Player-forward leaderboard module for the active season.",
    allowedVariants: ["podium", "compact_list"],
    defaultVariant: "podium",
    allowedSourceModes: ["automatic"],
    supportsManualSelection: false,
    minItems: 1,
    maxItems: 6,
    defaultItemLimit: 3,
    defaultTitle: "Top Performers",
    defaultDek: "The strongest current lines on the board.",
    allowSectionHeader: true,
  },
  {
    type: "recent_form",
    label: "Recent Form",
    description: "Latest verified session trail for readers following the current board.",
    allowedVariants: ["session_trail", "compact_list"],
    defaultVariant: "session_trail",
    allowedSourceModes: ["latest", "manual"],
    supportsManualSelection: true,
    manualSelectionType: "sessions",
    minItems: 1,
    maxItems: 6,
    defaultItemLimit: 3,
    defaultTitle: "Recent Form",
    defaultDek: "Fresh table results shaping the current read.",
    allowSectionHeader: true,
  },
];

export const DEFAULT_HOME_SETTINGS = {
  hero: {
    eyebrow: "Season 0 / Preseason / Current Board",
    title: "Para League",
    dek: "The first sessions are setting the board.",
  },
  modules: HOMEPAGE_MODULE_DEFINITIONS.map((module) => ({
    type: module.type,
    enabled: true,
    variant: module.defaultVariant,
    sourceMode: module.allowedSourceModes[0],
    selectedIds: [],
    title: module.defaultTitle,
    dek: module.defaultDek,
    itemLimit: module.defaultItemLimit,
    showSectionHeader: module.allowSectionHeader,
  })),
  updatedAt: null,
};
